# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-23 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=256, verbose_name='评论内容')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
            ],
            options={
                'db_table': 'weibo_comment',
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='关注时间')),
            ],
            options={
                'db_table': 'weibo_friend',
            },
        ),
        migrations.CreateModel(
            name='WeiBo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=500, verbose_name='微博内容')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('source', models.CharField(blank=True, max_length=20, null=True, verbose_name='发布来源')),
            ],
            options={
                'db_table': 'weibo',
            },
        ),
        migrations.CreateModel(
            name='WeiboImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/weibo', verbose_name='图片')),
                ('weibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weibo.WeiBo', verbose_name='关联微博')),
            ],
            options={
                'db_table': 'weibo_image',
            },
        ),
        migrations.CreateModel(
            name='WeiboUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('nickname', models.CharField(max_length=32, verbose_name='昵称')),
            ],
            options={
                'db_table': 'weibo_user',
            },
        ),
        migrations.AddField(
            model_name='weibo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weibo.WeiboUser', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='friend',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to='weibo.WeiboUser', verbose_name='关注用户'),
        ),
        migrations.AddField(
            model_name='friend',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to='weibo.WeiboUser', verbose_name='被关注用户'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weibo.WeiboUser', verbose_name='评论用户'),
        ),
        migrations.AddField(
            model_name='comment',
            name='weibo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weibo.WeiBo', verbose_name='评论微博'),
        ),
    ]
