# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-29 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weibo', '0002_weibouser_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='weibouser',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '正常'), (2, '限制用户'), (0, '已删除')], default=1, verbose_name='用户状态'),
        ),
    ]
