# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-24 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200224_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='accounts.Course'),
        ),
    ]
