# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-24 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('phone', models.IntegerField(max_length=11, verbose_name='电话')),
                ('address', models.CharField(max_length=256, verbose_name='地址')),
                ('is_valid', models.BooleanField(default=True, verbose_name='受否有效')),
                ('useraddrees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='UserDatil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(max_length=256, verbose_name='座右铭')),
                ('students', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
            ],
        ),
    ]
